---
- name: install some grafana plugins
  command: "{{ item }}"
  with_items:
    - grafana-cli plugins install ddurieux-glpi-app
    - grafana-cli plugins install grafana-clock-panel
    - grafana-cli plugins install grafana-piechart-panel
  notify:
    - restart grafana-server
