---
- name: insert/update httpd.conf
  blockinfile:
    path: /etc/httpd/conf/httpd.conf
    block: |
      <IfModule headers_module>
        Header set Access-Control-Allow-Origin "*"
        Header set Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE"
        Header set Access-Control-Allow-Credentials "true"
        Header set Access-Control-Allow-Headers "Origin,Content-Type,Accept,Authorization,App-Token,Session-Token"
      </IfModule>
  notify:
    - restart httpd
