---
- include_tasks: repo.yml
- include_tasks: install.yml  # install pkgs
- include_tasks: services.yml  # running services
- include_tasks: security.yml # config firewall
- include_tasks: add_plugins.yml # add some grafana plugins
- include_tasks: conf_httpd.yml
