---
- name: Copy the glpi.conf
  template:
    src: glpi.conf.j2
    dest: /etc/httpd/conf.d/glpi.conf
    owner: root
    mode: 0600
  notify:
    - restart httpd

- name: Cron GLPI
  cron:
    name: "Cron GLPI"
    job: "/usr/bin/php /usr/share/glpi/front/cron.php &>/dev/null"
