---
packages:
 - wget
 - ntp
 - firewalld
 - cockpit
 - cockpit-networkmanager
 - cockpit-storaged
services:
 - sshd
 - ntpd
 - firewalld
 - cockpit
firewalld_services_enabled:
 - ssh
firewalld_ports_enabled:
 - 9090/tcp
